/**
 * APIMATICCalculatorLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const Environments = {

    /**
     * This environment connect to the LIVE calculator API
     */
    PRODUCTION: 'production',

};

module.exports = Environments;
